# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "uas" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  # kvm-amd
  # https://gist.github.com/CMCDragonkai/810f78ee29c8fce916d072875f7e1751
  
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d06b73c6-8da1-42ea-9926-9a25dad71818";
      fsType = "btrfs";
      options = [
        "subvol=root"
        "noatime"
        "nodiratime"
      ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/d06b73c6-8da1-42ea-9926-9a25dad71818";
      fsType = "btrfs";
      options = [
        "subvol=home"
        "noatime"
        "nodiratime"
      ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/d06b73c6-8da1-42ea-9926-9a25dad71818";
      fsType = "btrfs";
      options = [
        "subvol=nix"
        "noatime"
        "nodiratime"
      ];
    };
    
    fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/d06b73c6-8da1-42ea-9926-9a25dad71818";
      fsType = "btrfs";
      options = [
        "subvol=swap"
        "noatime"
      ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EF30-2E33";
      fsType = "vfat";
    };

  # swapDevices = [ ];
  swapDevices = [ { device = "/swap/swapfile"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  
}
